on: [push]

jobs:
  checks-syntax:
  runs-on: ubuntu-latest
  name: Check PHP Syntax
  steps:
  - name: Syntax Check
    id: phplint
    uses: overtrue/phplint@8.0
    with:
      path: .
      options: --exclude=*.log
  