on: [push]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    name: Check PHP Syntax
    steps:
    - name: Syntax Check with PHPlint
      id: phplint
      uses: overtrue/phplint@8.0
      with:
        path: .
        options: --exclude=*.log
